FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY api/ /app/api/
COPY src/ /app/src/

EXPOSE 5000

ENV PYTHONPATH=/app

CMD ["python", "/app/api/app.py"]